version: "3"

services:
  db:
    build:
      context: .
    environment:
      - POSTGRES_USER=${DB_SUPERUSER}
      - POSTGRES_PASSWORD=${DB_SUPERUSER_PASSWORD}
      - QUOTESC_PASSWORD=${DB_QUOTESC_PASSWORD}
    ports:
      - ${DB_PORT}:5432
