version: "3"

services:
  db:
    #image: quotescdb 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_SUPERUSER}
      - POSTGRES_PASSWORD=${DB_SUPERUSER_PASSWORD}
      - QUOTESC_PASSWORD=${DB_QUOTESC_PASSWORD}
    ports:
      - ${DB_PORT}:5432
